#!/usr/bin/env python3
"""Generate SOURCES.md from data/needs.json + data/milestones.json (single source of truth)."""
import json, os
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
n = json.load(open(f"{R}/data/needs.json")); m = json.load(open(f"{R}/data/milestones.json"))
L = []
a = L.append
a("# SOURCES: every number on leuklogic.com\n")
a(f"Generated by `_build/make_sources.py` from `data/needs.json` and `data/milestones.json`. Data retrieved **{n['retrieved']}**.")
a("Each figure was read from the provider's own response at build time by `_build/fetch_data.py` (raw responses kept in `_build/receipts/`);")
a("the build script also asserts that the cited pages still say what we quote. Rule: a figure we cannot verify at its source is dropped, never guessed.\n")
a("## Present-day gaps (homepage tiles and `/needs/`)\n")
a("| Need | Figure | Year | Source | Licence |\n|---|---|---|---|---|")
for x in n["needs"]:
    a(f"| {x['need']} | {x['stat_text']} | {x['year']} | [{x['indicator']}]({x['source_url']}) ({x['underlying_source']}) | [{x['licence']}]({x['licence_url']}) |")
a("\nAll six come from the World Bank World Development Indicators API (`api.worldbank.org/v2/country/WLD/indicator/<id>?mrnev=1`, most recent value), world aggregate. Attribution: World Bank, WDI, CC BY 4.0, with the underlying agency named in each row.")
a("Cross-check against Our World in Data (same agencies, read from its CSVs): undernourishment 8.5% (2023) and 8.2% (2024, FAO); safely managed water 73.7% (2024, JMP); electricity access 91.9% (2024). All agree with the WDI values or are a later year of the same series.")
a("One disagreement, stated plainly: slums. WDI says 23.2% (2022); the UN-Habitat series on OWID says 24.8% for both 2022 and 2024, so WDI lags a UN-Habitat revision. The site shows the WDI figure with its year.\n")
a("## The three ingredients (homepage)\n")
a("| Ingredient | Figure | Year | Source | Licence |\n|---|---|---|---|---|")
for x in n["ingredients"]:
    a(f"| {x['ingredient']} | {x['stat_text']} | {x['year']} | [link]({x['source_url']}) | {x['licence']} |")
a("\n## Milestones (homepage timeline)\n")
a("| Year | Milestone | Source |\n|---|---|---|")
for x in m["milestones"]:
    a(f"| {x['year']} | {x['title']}: {x['text']} | [{x['source_name']}]({x['source_url']}) |")
a("\n## Dropped (not shown on the site)\n")
for d in n["dropped"]:
    a(f"- **{d['figure']}** ({'verified' if d['verified'] else 'not verifiable at source'}): {d['reason']}")
a("\n## Not numbers, but also sourced\n")
a("- Fonts: Fraunces and Figtree, SIL Open Font License 1.1, self-hosted (`fonts/`), fetched once from Fontsource via jsDelivr.")
a("- Film V01 and keyframes: made with AI tools (visuals and narration), labelled as AI-generated everywhere they appear. A vision, not footage of real events.")
a("- \"9 free tools\": the nine pages under `/tools/` that already existed.")
a("- No visitor counts, pledge counters, testimonials or user numbers appear anywhere. A global pledge counter would need a backend; see README.")
open(f"{R}/SOURCES.md", "w").write("\n".join(L) + "\n")
print("SOURCES.md written")
